# logger
logging_strategy: steps
logging_steps: 1
save_strategy: epoch
save_total_limit: 1
report_to: wandb
output_dir: dummy
overwrite_output_dir: True

# train
num_train_epochs: 1000
learning_rate: 2e-6
weight_decay: 0.01
max_grad_norm: 1.0
warmup_steps: 1000
fp16: False
optim: adamw_torch
lr_scheduler_type: linear
gradient_accumulation_steps: 1
per_device_train_batch_size: 8 # dummy if dynamic batching

# evaluation
per_device_eval_batch_size: 1
evaluation_strategy: steps
eval_steps: 1000
