defaults:
  - _self_
  - dataset: dist2
  - lm: qwen3
  - trainer: sft

# overwrite experiment config
name: qwen3-0.6B-dist@10%
dataset:
  processing:
    cropping:             True
    masking:              True
    concatenation:        True
    concatenation_ratio:  0.10

hydra:
  output_subdir: null
  run:
    dir: .