defaults:
  - dataset: dplm_pt
  - lm: qwen3
  - trainer: pt
  - _self_

# overwrite experiment config
name: dplm@pt@0107

lm:
  model_dir: /GenSIvePFS/users/lutianyu/lf/utils/qwen_utils/checkpoints//qwen3/Qwen3-4B

hydra:
  output_subdir: null
  run:
    dir: .