defaults:
  - _self_
  - dataset: pdb
  - lm: progen2
  - trainer: progen2

name: progen2-dplm2-struct
trainer:
  output_dir: /AIRvePFS/ai4science/users/tianyu/LLMFolding-structure/output/checkpoints/struct
dataset:
  train_task: struct_lm
  eval_task: folding_lm

hydra:
  output_subdir: null
  run:
    dir: .