defaults:
  - dataset: dist3
  - lm: qwen3
  - trainer: sft
  - _self_

# overwrite experiment config
name: qwen3-0.6B-dist3-0@pt

dataset:
  processing:
    cropping:             True
    masking:              False
    concatenation:        False
    concatenation_ratio:  0.0

hydra:
  output_subdir: null
  run:
    dir: .