defaults:
  - dataset: dist3-1_folding_sft
  - lm: qwen3
  - trainer: sft
  - _self_

# overwrite experiment config
name: dist3-1@folding_sft

lm:
  model_dir: /GenSIvePFS/users/lutianyu/lf/output/checkpoints/qwen3-0.6B-dist3@pt/checkpoint-30000

hydra:
  output_subdir: null
  run:
    dir: .