model_type:   qwen3_0.6B
# model_dir:    /GenSIvePFS/users/lutianyu/lf/output/checkpoints/qwen3@rcsb+swissprot@debug_folding+sequence/checkpoint-20000
model_dir:    /GenSIvePFS/users/lutianyu/lf/utils/qwen_utils/checkpoints/qwen3/tmp/debug