model_type:   qwen3_0.6B
# model_dir:    /GenSIvePFS/users/lutianyu/lf/utils/qwen_utils/checkpoints/qwen3/Qwen3-0.6B
model_dir:    /GenSIvePFS/users/lutianyu/lf/output/checkpoints/qwen3-0.6B@40/1.5/1.5(2/3/5)@pt/checkpoint-30000
