type: dist

train:
  - /GenSIvePFS/users/lutianyu/lf/dataset/sequence/uniref50/train.parquet
  - /GenSIvePFS/users/lutianyu/lf/dataset/sequence/uniref50/train.parquet
  - /GenSIvePFS/users/lutianyu/lf/dataset/folding/dplm2/train.parquet

weight:
  - 0.4
  - 0.4
  - 0.2

eval:
  - /GenSIvePFS/users/lutianyu/lf/dataset/sequence/uniref50/eval.parquet
  - /GenSIvePFS/users/lutianyu/lf/dataset/sequence/uniref50/eval.parquet
  - /GenSIvePFS/users/lutianyu/lf/dataset/folding/dplm2/eval.parquet