type: dist

train:
  # - /GenSIvePFS/users/lutianyu/lf/dataset/dataset_dist2/sequence/uniref50/train.parquet
  # - /GenSIvePFS/users/lutianyu/lf/dataset/dataset_dist2/structure/unicluster40/train.parquet
  - /GenSIvePFS/users/lutianyu/lf/dataset/dataset_dist2/folding/unicluster40/train.parquet

weight:
  # - 0.2
  # - 0.3
  # - 0.5
  - 1.0

eval:
  - /GenSIvePFS/users/lutianyu/lf/dataset/dataset_dist2/sequence/uniref50/eval.parquet
  - /GenSIvePFS/users/lutianyu/lf/dataset/dataset_dist2/structure/unicluster40/eval.parquet
  - /GenSIvePFS/users/lutianyu/lf/dataset/dataset_dist2/folding/unicluster40/eval.parquet
  # target benchmark
  - /GenSIvePFS/users/lutianyu/lf/dataset/dataset_dist2/folding/benchmark/*.parquet

processing:
  cropping:             True
  masking:              False
  concatenation:        False
  concatenation_ratio:  0.0
