type: dist

train:
  - /GenSIvePFS/users/lutianyu/lf/dataset/structure/rcsb+swissprot_dplm/train/rcsb.parquet
  - /GenSIvePFS/users/lutianyu/lf/dataset/structure/rcsb+swissprot_dplm/train/swissprot.parquet

weight:
  - 0.1
  - 0.9

eval:
  - /GenSIvePFS/users/lutianyu/lf/dataset/folding/rcsb+swissprot_dplm/eval/*.parquet