type: dist

train:
  - /GenSIvePFS/users/lutianyu/lf/dataset/rcsb+swissprot/train/swissprot.json
  - /GenSIvePFS/users/lutianyu/lf/dataset/rcsb+swissprot/train/rcsb.json

weight:
  - 0.9
  - 0.1

eval:
  - /GenSIvePFS/users/lutianyu/lf/dataset/rcsb+swissprot/eval/cameo2022.json
  - /GenSIvePFS/users/lutianyu/lf/dataset/rcsb+swissprot/eval/casp15.json
  - /GenSIvePFS/users/lutianyu/lf/dataset/rcsb+swissprot/eval/casp16.json
  - /GenSIvePFS/users/lutianyu/lf/dataset/rcsb+swissprot/eval/dev.json
  - /GenSIvePFS/users/lutianyu/lf/dataset/rcsb+swissprot/eval/rcsb.json
